version: "3.9"
services:
  web:
    container_name: "web"
    build: ./web
    ports:
      - "3000:5000"
    networks:
      - frontend
  spring:
    container_name: "spring"
    build: ./spring
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    networks:
      - frontend
      - backend
  db:
    container_name: "db"
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456ok
      POSTGRES_DB: postgres
    expose:
      - "5432"
    networks:
      - backend
networks:
  frontend:
  backend:

